# BASIC PYTHON 5

## NumPy

> `Numpy` (**Numerical Python**) adalah library yang fokus pada scientific computing. NumPy memiliki kemampuan dalam membuat n-dimensional array mirip seperti array pada Python.

### Array

> Array numpy secara umum merupakan kumpulan tipe data homogen yang berarti berisi objek (tipe data) satu jenis.

![img](http://solutionhacker.com/wp-content/uploads/2017/03/python-array.jpg)

![img](https://miro.medium.com/max/1288/1*SGqhI_WpSaEr17wo8ycUhg.png
)

### INSTALL & IMPORT NUMPY

> Install: `conda install`

#### 1. BASIC OPERATION

In [2]:
# contoh import library numpy
import numpy as np

In [5]:
# contoh dengan list
list1 = [1, 2, 3, 4]
print(list1)

[1, 2, 3, 4]


In [6]:
# contoh list ke array
np.array(list1)

array([1, 2, 3, 4])

In [12]:
# buat array
list2 = [[5, 6, 7, 8], [9, 10, 11, 12]]
arr2 = np.array(range(1, 7))  # dari tuple
arr3 = np.array(list2)  # array 2D (matrix)

In [13]:
list2

[[5, 6, 7, 8], [9, 10, 11, 12]]

In [14]:
# cek tipe array
print(type(list1))
print(type(arr3))

<class 'list'>
<class 'numpy.ndarray'>


In [15]:
# cek dimensi array
print("dimensi array 2 = ", arr2.ndim)  # vector
print("dimensi array 3 = ", arr3.ndim)  # matrix

dimensi array 2 =  1
dimensi array 3 =  2


In [16]:
# cek shape array
print(arr2.shape)
print(arr3.shape)

(6,)
(2, 4)


In [18]:
list2[1][0]

9

In [19]:
# cek size array
print(arr2.size)
print(arr3.size)

6
8


> Array tidak harus dalam bentuk nilai int atau float, tetapi bisa boolan, string, dll

In [20]:
# contoh array dengan boolean
b = np.array([[True, False], [True, False]])

In [22]:
# print array boolean
print(b)
print(type(b))
print(b.size)
print(b.shape)

[[ True False]
 [ True False]]
<class 'numpy.ndarray'>
4
(2, 2)


In [23]:
# rubah list ke matrix
list2 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
mat1 = np.array(list2)

In [24]:
# print matrix
print(mat1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [25]:
# indexin matrix
print(mat1[0], mat1[1], mat1[2])

[1 2 3] [4 5 6] [7 8 9]


In [27]:
# ganti element / nilai
mat1[1][0] = 5
print(mat1)

[[1 2 3]
 [5 5 6]
 [7 8 9]]


> Kita dapat melihat tipe data pada array dengan `dtype`, dokumentasi:
>   1. https://numpy.org/doc/stable/user/basics.types.html
>   2. https://numpy.org/doc/stable/reference/arrays.dtypes.html

In [29]:
# buat array dengan tipe data tertentu
arr4 = np.array([1, 2, 3], dtype="int64")  # tipe data int32
print(arr4)
print(arr4.dtype)

[1 2 3]
int64


In [30]:
# contoh buat array dengan tipe data float
arr5 = np.array([[9.0, 8.0, 7.0], [6.0, 5.0, 4.0]])
print(arr5)
print(arr5.dtype)

[[9. 8. 7.]
 [6. 5. 4.]]
float64


In [31]:
# contoh buat array dengan tipe data string
arr6 = np.array([["halo", "halo"], ["halo2", "halo2"]])
print(arr6)
print(arr6.dtype)

[['halo' 'halo']
 ['halo2' 'halo2']]
<U5


In [32]:
# contoh buat aray dengna data berbeda
arr7 = np.array([[1, 1], [2.66, "halo2"]])
print(arr7)
print(arr7.dtype)

[['1' '1']
 ['2.66' 'halo2']]
<U32


#### 2. RANDOM

> NumPy juga mendukung 

In [3]:
# contoh fungsi rand
np.random.rand(4)

array([0.32774644, 0.4487843 , 0.07379091, 0.21242469])

In [4]:
# contoh fungsi rand
np.random.rand(3, 5)

array([[0.53779598, 0.45801837, 0.56320682, 0.91940205, 0.28950917],
       [0.09109969, 0.27422103, 0.84892889, 0.37458519, 0.72825795],
       [0.76954723, 0.15594124, 0.95617114, 0.50717865, 0.89997556]])

In [5]:
# contoh fungsi rand
np.random.rand(4, 2)

array([[0.16778336, 0.12274304],
       [0.33954814, 0.89756641],
       [0.95698329, 0.67167217],
       [0.42511923, 0.39752469]])

In [7]:
# contoh fungsi rand
np.random.rand(2, 3, 4)  # jumlah index, max, elemen

array([[[0.10043494, 0.90004802, 0.04383774, 0.92026059],
        [0.54715466, 0.57603691, 0.1278922 , 0.69102345],
        [0.91716762, 0.74343238, 0.41628697, 0.94235092]],

       [[0.3478506 , 0.56697911, 0.37556119, 0.95604204],
        [0.8543598 , 0.87811316, 0.50336108, 0.93912411],
        [0.49237179, 0.7771804 , 0.26408792, 0.7954567 ]]])

In [8]:
# contoh fungsi randint
np.random.randint(-3, 4, size=(3, 4))  # nilai minimal, nilai maximal-1, ukuran matrix

array([[ 0, -1, -2,  0],
       [-2,  0, -1,  0],
       [ 0,  0,  0,  0]])

In [11]:
# contoh fungsi randint
x = np.random.randint(0, 10, 10)
y = np.random.randint(0, 10, 10)

In [12]:
x, y

(array([2, 9, 1, 3, 4, 8, 5, 2, 4, 2]), array([2, 0, 9, 2, 7, 9, 0, 4, 4, 1]))

In [13]:
# contoh fungsi randn
np.random.randn(4)

array([0.25453916, 0.1760349 , 0.357388  , 1.36093692])

In [14]:
# contoh fungsi randn
np.random.randn(4, 3)

array([[-1.55220804,  0.21564581,  0.31171296],
       [ 1.4242104 ,  0.15690396,  0.14796179],
       [-0.71934454, -0.63035137, -0.81478389],
       [ 0.05625845, -0.33354663,  0.18858377]])

In [19]:
# contoh fungsi randn
np.random.seed(0)
x = np.random.randn(2, 2, 4)

In [20]:
# nilai fungsi randn
x

array([[[ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ],
        [ 1.86755799, -0.97727788,  0.95008842, -0.15135721]],

       [[-0.10321885,  0.4105985 ,  0.14404357,  1.45427351],
        [ 0.76103773,  0.12167502,  0.44386323,  0.33367433]]])

In [21]:
# contoh transpose
x.T

array([[[ 1.76405235, -0.10321885],
        [ 1.86755799,  0.76103773]],

       [[ 0.40015721,  0.4105985 ],
        [-0.97727788,  0.12167502]],

       [[ 0.97873798,  0.14404357],
        [ 0.95008842,  0.44386323]],

       [[ 2.2408932 ,  1.45427351],
        [-0.15135721,  0.33367433]]])

>  Kira bisa mengetahui nilai min, max, dan argument (mirip index) dari suatu array, dengan `min`, `max`, `agrmin`, `argmax`.

In [23]:
# contoh masukkan input ke variabel
np.random.seed(0)
rand1 = np.random.randint(1, 10, 8)
rand1

array([6, 1, 4, 4, 8, 4, 6, 3])

In [24]:
# print nilai max, min, argmax, argmin
print("Nilai maksimum:", rand1.max())
print("Nilai minimum:", rand1.min())
print("Nilai arg max:", rand1.argmax())
print("Nilai arg min:", rand1.argmin())

Nilai maksimum: 8
Nilai minimum: 1
Nilai arg max: 4
Nilai arg min: 1


In [25]:
# menggunakan random.normal untuk distribusi normal / gaussian
norm_array = np.random.normal(3, 0.5, 8)  # mean, std, size
print(norm_array)

[3.47504421 2.9243214  2.94839057 3.20529925 3.07202179 3.72713675
 3.38051886 3.06083751]


> NumPy memiliki banyak fungsi yang berkaitan dengan array dan pembentikannya. Beberapa diantaranya adalah `zeros` (membuat array dengan nilai 0), `ones` (membuat array dengan nilai 1), `full` (membuat array dengan nilai yang diisi nilai tertentu).

In [26]:
# contoh zeros
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [29]:
# matrix 0
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [30]:
# contoh ones
np.ones(1)*5

array([5.])

In [31]:
# contoh ones
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [34]:
# contoh membuat matrix
np.matrix(np.ones((4, 5)))

matrix([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [35]:
# matrix berisi all 1
np.ones((4, 2, 2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [36]:
# contoh full
np.full((2, 3), 10)

array([[10, 10, 10],
       [10, 10, 10]])

In [37]:
# contoh full like
np.full_like(x, 5)

array([[[5., 5., 5., 5.],
        [5., 5., 5., 5.]],

       [[5., 5., 5., 5.],
        [5., 5., 5., 5.]]])

In [38]:
# contoh full like
np.full_like(x.T, 2)

array([[[2., 2.],
        [2., 2.]],

       [[2., 2.],
        [2., 2.]],

       [[2., 2.],
        [2., 2.]],

       [[2., 2.],
        [2., 2.]]])

In [39]:
# identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [40]:
# contoh repeat untuk menduplikasi array sebanyak n kali
arr8 = np.array([[1, 2, 3, 4, 5]])

In [47]:
rep1 = np.repeat(arr8, 3, axis=0)

In [42]:
print(arr8)

[[1 2 3 4 5]]


In [48]:
print(rep1)

[[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]


In [49]:
# contoh membuat matrix dengan kondisi tertentu

# 1 1 1 1 1
# 1 0 0 0 1
# 1 0 9 0 1
# 1 0 0 0 1
# 1 1 1 1 1

In [50]:
# step 1
output = np.ones((5, 5))
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [60]:
# cara 1: replace index
output[1][1:-1] = 0
output[2][1:-1] = 0
output[3][1:-1] = 0
output[2][2] = 9

In [61]:
# hasil cara 1
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [64]:
# cara 2: buat nilai dari np.zeros
output2 = np.ones((5, 5))
output2

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [67]:
z = np.zeros((3, 3))
z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [69]:
output2[1:4, 1:4] = z
output2

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [70]:
output2[2][2] = 9
output2

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

> Dokumentasi lanjutan mengenai array: https://numpy.org/doc/stable/user/basics.creation.html#arrays-creation

#### 3. MANIPULATE ARRAY

> Ada beberapa fungsi lain yang sering dipakai untuk manipulasi array, beberapa diantaranya adalah `asarray()`, `arange()`, dan `reshape()`.

In [3]:
# contoh asarray, mengubah input menjadi array
list1 = [1, 2, 3, 4]
np.asarray(list1)

array([1, 2, 3, 4])

In [14]:
# contoh arrange, untuk mendapatkan array yang intervalnya sama
print("Interval 1: ", np.arange(1, 10, 1))
print("Interval 2: ", np.arange(1, 20, 2))  # start, end-1, interval

Interval 1:  [1 2 3 4 5 6 7 8 9]
Interval 2:  [ 1  3  5  7  9 11 13 15 17 19]


In [11]:
# contoh reshape, mengubah shape array
arr = np.array([(1, 2, 3), (4, 5, 6), (7, 8, 9), (10, 11, 12)])
print(arr)
print("Shape awal: ", arr.shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Shape awal:  (4, 3)


In [12]:
# lakukan reshape, perkalian jumlah shape array harus sama
print(arr.reshape(2, 6))
print("Setelah di reshape: ", arr.reshape(2, 6).shape)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
Setelah di reshape:  (2, 6)


In [15]:
# perbedaan dengan transpose
print(arr.T)
print("\n", arr.T.shape)

[[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]

 (3, 4)


> Selain itu, kita juga bisa menambahkan suatu array pada NumPy, mirip append pada list.

> Cara dengan `hstack` (append data secara horizontal) dan `vstack` (append secara vertikal).

In [16]:
# contoh hstack dan vstack vector
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

In [18]:
# print hasil stack
print("Vector hstack:", np.hstack((v2, v1)))
print("Vector vstack:\n", np.vstack((v1, v2)))

Vector hstack: [4 5 6 1 2 3]
Vector vstack:
 [[1 2 3]
 [4 5 6]]


> Jika `hstack` pada array (vector) maka dia akan tetap jadi vector, tetapi jika `vstack` maka dia akan berubah menjadi matrix.

In [20]:
# print dimensi stack
print("Dimensi vector hstack:", np.hstack((v2, v1)).ndim)
print("Dimensi vector vstack:", np.vstack((v1, v2)).ndim)

Dimensi vector hstack: 1
Dimensi vector vstack: 2


In [21]:
# contoh hstack dan vstack matrix
m1 = np.ones((4, 3))
m2 = np.zeros((4, 3))

In [22]:
m1

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [23]:
m2

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [25]:
# print hasil stack
print("Vector hstack:", np.hstack((m1, m2)))
print("\nVector vstack:\n", np.vstack((m1, m2)))

Vector hstack: [[1. 1. 1. 0. 0. 0.]
 [1. 1. 1. 0. 0. 0.]
 [1. 1. 1. 0. 0. 0.]
 [1. 1. 1. 0. 0. 0.]]

Vector vstack:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [26]:
# print dimensi dan shape stack
print("Dimensi vector hstack:", np.hstack((m1, m2)).ndim)
print("Shape vector hstack:", np.hstack((m1, m2)).shape)

print("\nDimensi vector vstack:", np.vstack((m1, m2)).ndim)
print("Shape vector hstack:", np.vstack((m1, m2)).shape)

Dimensi vector hstack: 2
Shape vector hstack: (4, 6)

Dimensi vector vstack: 2
Shape vector hstack: (8, 3)


#### 4. OPERASI ARRAY

> Modul pada NumPy mendukung operasi sederhana array matematika.

> Dokumentasi: https://numpy.org/doc/stable/reference/routines.math.html

In [27]:
# buat array baru (random)
arr1 = np.random.randint(1, 10, 10)
print("array1 =", arr1)

array1 = [5 8 9 2 1 9 1 1 7 6]


In [28]:
# buat array baru kedua
arr2 = np.random.randint(1, 10, 10)
print("array1 =", arr2)

array1 = [1 9 6 3 3 4 3 4 9 1]


In [32]:
# contoh operasi elemen array (dengan operator)
print("tambah  = ", arr1 + arr2)
print("kurang  = ", arr1 - arr2)
print("kali    = ", arr1 * arr2)
print("bagi    = ", arr1 / arr2)
print("modulo  = ", arr1 % arr2)
print("pangkat = ", arr1 ** arr2)

tambah  =  [ 6 17 15  5  4 13  4  5 16  7]
kurang  =  [ 4 -1  3 -1 -2  5 -2 -3 -2  5]
kali    =  [ 5 72 54  6  3 36  3  4 63  6]
bagi    =  [5.         0.88888889 1.5        0.66666667 0.33333333 2.25
 0.33333333 0.25       0.77777778 6.        ]
modulo  =  [0 8 3 2 1 1 1 1 7 0]
pangkat =  [        5 134217728    531441         8         1      6561         1
         1  40353607         6]


> Kita dapat menggunakan beberapa function yang disediakan NumPy, diantatanya adalah `sqrt()`, `exp()`, `add()`, `multiply()`, `min()`, `max()`, `subtract()`, dan `divide()`.

In [33]:
# fungsi sqrt
np.sqrt(1)

1.0

In [34]:
# fungsi exp
np.exp(arr1)

array([1.48413159e+02, 2.98095799e+03, 8.10308393e+03, 7.38905610e+00,
       2.71828183e+00, 8.10308393e+03, 2.71828183e+00, 2.71828183e+00,
       1.09663316e+03, 4.03428793e+02])

In [35]:
# fungsi max
np.max(arr1)

9

In [36]:
# fungsi min
np.min(arr1)

1

In [37]:
# fungsi add
np.add(arr1, arr2)

array([ 6, 17, 15,  5,  4, 13,  4,  5, 16,  7])

In [40]:
# fungsi subtract
np.subtract(3, arr1)

array([-2, -5, -6,  1,  2, -6,  2,  2, -4, -3])

In [42]:
# fungsi divide
np.divide(arr1, 2)

array([2.5, 4. , 4.5, 1. , 0.5, 4.5, 0.5, 0.5, 3.5, 3. ])

In [43]:
# fungsi multiply
np.multiply(arr1, arr2)

array([ 5, 72, 54,  6,  3, 36,  3,  4, 63,  6])

In [45]:
# fungsi sum
np.sum(arr2)

43

In [46]:
# contoh fungsi sum matrix
arr3 = np.array([[1, 2], [3, 4]])

print(np.sum(arr3))  # sum semua elemen
print(np.sum(arr3, axis=0))  # sum element pada kolom
print(np.sum(arr3, axis=1))  # sum element pada baris

10
[4 6]
[3 7]


> Pada NumPy juga disediakan fungsi untuk melakukan perkalian matrix (bukan elementnya), yaitu dengan `dot()` atau `matmul()`.

> Dokumentasi: https://numpy.org/doc/stable/reference/generated/numpy.dot.html


![img](https://saintif.com/wp-content/uploads/2020/07/image-18.png)

In [47]:
# contoh fungsi dot dan matmul (prefered: 2D)
arr3 = np.array([1, 2])
arr4 = np.array([3, 4])

In [49]:
# print hasil
print("dengan dot() arr3.arr4 = ", np.dot(arr3, arr4))
print("dengan matmul() arr3.arr4 = ", np.matmul(arr3, arr4))

dengan dot() arr3.arr4 =  11
dengan matmul() arr3.arr4 =  11


In [51]:
# contoh dengan 2D array (matrix)
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])

In [52]:
# haril dot
print("x.y:\n", np.dot(x, y))
print("y.x:\n", np.dot(y, x))

x.y:
 [[19 22]
 [43 50]]
y.x:
 [[23 34]
 [31 46]]


In [53]:
# haril matmul
print("x.y:\n", np.matmul(x, y))
print("y.x:\n", np.matmul(y, x))

x.y:
 [[19 22]
 [43 50]]
y.x:
 [[23 34]
 [31 46]]


#### 5. ALJABAR LINEAR

> Keunggulan NumPy array dibanding list adalah konsumsi memori dan runtime yang lebih kecil dan cepat, serta mempermudah dalam melakukan operasi aljabar linear, terutama operasi pada vektor (1D array) dan matrix (2D array) dengan `linalg()`.

> Dokumentasi: https://numpy.org/doc/stable/reference/routines.linalg.html


> **Contoh Soal 1**:

> a) $2x_{1}$ + $3x_{2}$ = 10

> b) $x_{1}$ + $2x_{2}$ = 5


In [55]:
# step 1: masukkan persamaan dalam bentuk list
hitungan = [[2, 3], [1, 2]]
hasil = [10, 5]

In [56]:
# step 2: rubah ke array
arr_hit = np.asarray(hitungan)
arr_has = np.asarray(hasil)

In [59]:
print("Array hitung: \n", arr_hit)
print("\nArray hasil: \n", arr_has)

Array hitung: 
 [[2 3]
 [1 2]]

Array hasil: 
 [10  5]


In [72]:
# solve dengan fungsi `linalg.solve(a, b)`
hasil_pers = np.linalg.solve(arr_hit, arr_has)
print("hasil perhitungan linear aljabar =", hasil_pers)
print("hasil x1 adalah =", hasil_pers[0])
print("hasil x2 adalah =", hasil_pers[1])

hasil perhitungan linear aljabar = [5. 0.]
hasil x1 adalah = 5.0
hasil x2 adalah = 0.0


In [64]:
# cek hasil persamaan
np.allclose(np.dot(arr_hit, hasil_pers), arr_has)

True

In [74]:
# cari determinan
np.linalg.det(arr_hit)

1.0

> **Contoh Soal 2:**

> $x_{1}$  + $4x_{2}$ + $2x_{3}$ = 20

> $2x_{1}$ + $3x_{2}$ + $6x_{3}$ = 25

> $3x_{1}$ + $x_{2}$  + $2x_{3}$ = 16

In [65]:
# contoh buat list dulu
hit_a = [[1, 4, 2], [2, 3, 6], [3, 1, 2]]
has_a = [20, 25, 16]

In [69]:
# dibuat dalam bentuk array
hit_arr_a = np.asarray(hit_a)
has_arr_a = np.asarray(has_a)

print("Array_hitung: \n", hit_arr_a)
print("\nArray_hasil: \n", has_arr_a)

Array_hitung: 
 [[1 4 2]
 [2 3 6]
 [3 1 2]]

Array_hasil: 
 [20 25 16]


In [71]:
# solve persamaan lialg.solve
hasil_pers1 = np.linalg.solve(hit_arr_a, has_arr_a)
print("hasil perhitungan linear aljabar =", hasil_pers1)
print("hasil x1 adalah =", hasil_pers1[0])
print("hasil x2 adalah =", hasil_pers1[1])
print("hasil x3 adalah =", hasil_pers1[2])

hasil perhitungan linear aljabar = [3.28571429 3.52380952 1.30952381]
hasil x1 adalah = 3.285714285714286
hasil x2 adalah = 3.5238095238095246
hasil x3 adalah = 1.309523809523809


In [73]:
# cek hasil persamaan
np.allclose(np.dot(hit_arr_a, hasil_pers1), has_arr_a)

True

#### 6. BASIC STATISTIC

> Dokumentasi: https://numpy.org/doc/stable/reference/routines.statistics.html


In [75]:
# contoh buat array baru
norm_arr = np.random.normal(5, 0.5, 10)
print(norm_arr)

[4.07794232 6.16652435 3.81239216 4.80048405 4.95992574 4.9498822
 4.0898645  4.65097918 5.09595204 4.8534647 ]


In [76]:
# contoh beberapa statistical function
print("Hasil min        =", np.min(norm_arr))
print("Hasil max        =", np.max(norm_arr))
print("Hasil mean       =", np.mean(norm_arr))
print("Hasil median     =", np.median(norm_arr))
print("Hasil stdev      =", np.std(norm_arr))
print("Hasil quantile   =", np.quantile(norm_arr, .25))
print("Hasil percentile =", np.percentile(norm_arr, .25))

Hasil min        = 3.8123921580205566
Hasil max        = 6.166524353662672
Hasil mean       = 4.745741125762879
Hasil median     = 4.826974377781703
Hasil stdev      = 0.632429597578569
Hasil quantile   = 4.230143172942444
Hasil percentile = 3.8183670367192897
